#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */


    fsp_err_t err;
    /* Open SLCDC driver */
    err = R_SLCDC_Open(&g_slcdc0_ctrl, &g_slcdc0_cfg);
    /* Handle any errors. This function should be defined by the user. */
    assert(FSP_SUCCESS == err);
    /* When using internal boost mode this delay is required to allow the boost circuit to charge. See RA4M1 User's
     * Manual (R01UH0887EJ0100) 8.2.18 "Segment LCD Source Clock Control Register (SLCDSCKCR)" for details. */
    R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_MILLISECONDS);
    /* Start SLCDC output */
    err = R_SLCDC_Start(&g_slcdc0_ctrl);
    assert(FSP_SUCCESS == err);

    /* Set Display Area of SLCDC driver.*/
//    err = R_SLCDC_SetDisplayArea(&g_slcdc0_ctrl, SLCDC_DISP_A);
//    assert(FSP_SUCCESS == err);
    //准备并写入段显示数据,第一个数码管显示1
    uint8_t segment_data_num1[] = {
    0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,0x00,
    0x00,0x6
    };
    R_SLCDC_Write(&g_slcdc0_ctrl, 0, segment_data_num1, sizeof(segment_data_num1));
    R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);

    //准备并写入段显示数据,第二个数码管显示2
    uint8_t segment_data_num2[] = {
    0xE,0x3};
    R_SLCDC_Write(&g_slcdc0_ctrl, 15, segment_data_num2, sizeof(segment_data_num2));
    R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);

    //准备并写入段显示数据,第三个数码管显示3
    R_SLCDC_Modify(&g_slcdc0_ctrl, 22, 0xA, 0xF);
    R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);
    R_SLCDC_Modify(&g_slcdc0_ctrl, 23, 0x7, 0xF);
    R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);

    //准备并写入段显示数据,第四个数码管显示4
    R_SLCDC_Modify(&g_slcdc0_ctrl, 24, 0x3, 0xF);
    R_SLCDC_Modify(&g_slcdc0_ctrl, 29, 0x6, 0xF);
    R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);

    //准备并写入段显示数据,第五个数码管显示5
    R_SLCDC_Modify(&g_slcdc0_ctrl, 30, 0xB, 0xF);
    R_SLCDC_Modify(&g_slcdc0_ctrl, 39, 0x5, 0xF);
    R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);

    //准备并写入段显示数据,第六个数码管显示6
    R_SLCDC_Modify(&g_slcdc0_ctrl, 40, 0xF, 0xF);
    R_SLCDC_Modify(&g_slcdc0_ctrl, 41, 0x5, 0xF);
    R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);

    while(1)
    {
        //清空0-41段
        uint8_t segment_data_num_off[41+1] ;
        for(int i=0;i<=41;i++)
            segment_data_num_off[i]=0;
        R_SLCDC_Write(&g_slcdc0_ctrl, 0, segment_data_num_off, sizeof(segment_data_num_off));
        R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);

        //全部点亮
        uint8_t segment_data_num_on[41+1] ;
        for(int i=0;i<=41;i++)
            segment_data_num_on[i]=0xf;
        R_SLCDC_Write(&g_slcdc0_ctrl, 0, segment_data_num_on, sizeof(segment_data_num_on));
        R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);

        //准备并写入段显示数据,第一个数码管显示1
        R_SLCDC_Modify(&g_slcdc0_ctrl, 3, 0x0, 0xF);
        R_SLCDC_Modify(&g_slcdc0_ctrl, 11, 0x6, 0xF);

        //准备并写入段显示数据,第二个数码管显示2
        R_SLCDC_Modify(&g_slcdc0_ctrl, 15, 0xE, 0xF);
        R_SLCDC_Modify(&g_slcdc0_ctrl, 16, 0x3, 0xF);

        //准备并写入段显示数据,第三个数码管显示3
        R_SLCDC_Modify(&g_slcdc0_ctrl, 22, 0xA, 0xF);
        R_SLCDC_Modify(&g_slcdc0_ctrl, 23, 0x7, 0xF);

        //准备并写入段显示数据,第四个数码管显示4
        R_SLCDC_Modify(&g_slcdc0_ctrl, 24, 0x3, 0xF);
        R_SLCDC_Modify(&g_slcdc0_ctrl, 29, 0x6, 0xF);

        //准备并写入段显示数据,第五个数码管显示5
        R_SLCDC_Modify(&g_slcdc0_ctrl, 30, 0xB, 0xF);
        R_SLCDC_Modify(&g_slcdc0_ctrl, 39, 0x5, 0xF);

        //准备并写入段显示数据,第六个数码管显示6
        R_SLCDC_Modify(&g_slcdc0_ctrl, 40, 0xF, 0xF);
        R_SLCDC_Modify(&g_slcdc0_ctrl, 41, 0x5, 0xF);
        R_BSP_SoftwareDelay (2000, BSP_DELAY_UNITS_MILLISECONDS);


    }


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
